# Generated by Django 3.1.7 on 2021-03-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210329_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmedia',
            name='filename',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='filename',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='variantmedia',
            name='filename',
            field=models.ImageField(upload_to='media'),
        ),
    ]
