# Generated by Django 3.1.7 on 2021-04-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210329_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmedia',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='variantmedia',
            name='filename',
        ),
        migrations.AddField(
            model_name='collectionmedia',
            name='url',
            field=models.CharField(default='https://cdn.allbirds.com/image/upload/v1571355713/icons/allbirds-logo.svg', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmedia',
            name='url',
            field=models.CharField(default='https://cdn.allbirds.com/image/upload/v1571355713/icons/allbirds-logo.svg', max_length=1023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantmedia',
            name='url',
            field=models.CharField(default='https://cdn.allbirds.com/image/upload/v1571355713/icons/allbirds-logo.svg', max_length=1023),
            preserve_default=False,
        ),
    ]
